<?php

/**
 * Plantilla de carpetas estándar para obras peruanas.
 *
 * El orden de creación viene dado por el orden en este array — no por el
 * nombre. Por eso los nombres no llevan prefijo numérico.
 */

return [
    [
        'nombre' => 'GESTION_CONTRACTUAL',
        'descripcion' => 'Contratos, garantías, adicionales y liquidaciones contractuales.',
        'subcarpetas' => [
            'Contrato',
            'Bases_Integradas',
            'TDR',
            'Propuesta_Tecnica',
            'Propuesta_Economica',
            'Garantias',
            'Adelantos',
            'Seguros',
            'Cartas_Fianza',
            'Adicionales',
            'Deductivos',
            'Ampliaciones_Plazo',
            'Penalidades',
            'Resoluciones',
            'Liquidacion_Contrato',
        ],
    ],
    [
        'nombre' => 'EXPEDIENTE_TECNICO',
        'descripcion' => 'Planos, memoria, especificaciones, estudios y presupuesto.',
        'subcarpetas' => [
            [
                'nombre' => 'Planos',
                'subcarpetas' => [
                    'Arquitectura',
                    'Estructuras',
                    'Electricas',
                    'Sanitarias',
                    'Mecanicas',
                    'As_Built',
                ],
            ],
            'Memoria_Descriptiva',
            'Especificaciones_Tecnicas',
            [
                'nombre' => 'Estudios',
                'subcarpetas' => [
                    'Suelos',
                    'Topografia',
                    'Hidrologia',
                    'Impacto_Ambiental',
                    'Trafico',
                ],
            ],
            'Metrados',
            'Presupuesto',
            'Analisis_Precios_Unitarios',
            'Formulas_Polinomicas',
            'Cronograma_Obra',
            'Compatibilizacion',
        ],
    ],
    [
        'nombre' => 'CORRESPONDENCIA',
        'descripcion' => 'Cartas, oficios, memorandos, actas y notificaciones.',
        'subcarpetas' => [
            'Cartas_Enviadas',
            'Cartas_Recibidas',
            'Oficios',
            'Memorandos',
            'Actas',
            'Notificaciones',
            'Correos_Importantes',
            'Cargo_Recepcion',
        ],
    ],
    [
        'nombre' => 'VALORIZACIONES',
        'descripcion' => 'Valorizaciones mensuales, sustentos, panel fotográfico y pagos.',
        'subcarpetas' => [
            'Valorizaciones_Mensuales',
            'Sustento_Metrados',
            'Panel_Fotografico',
            'Conformidades',
            'Estados_Pago',
            'Facturas',
            'Reajustes',
            'Mayores_Metrados',
        ],
    ],
    [
        'nombre' => 'CALIDAD_QAQC',
        'descripcion' => 'Protocolos, ensayos, no conformidades y dossier de calidad.',
        'subcarpetas' => [
            'Protocolos',
            'Ensayos_Laboratorio',
            'Certificados_Calidad',
            'Dosificaciones',
            'Checklists',
            'No_Conformidades',
            'Acciones_Correctivas',
            'Liberaciones',
            'Dossier_Calidad',
        ],
    ],
    [
        'nombre' => 'SSOMA',
        'descripcion' => 'ATS, IPERC, permisos, capacitaciones, inspecciones y reportes.',
        'subcarpetas' => [
            'ATS',
            'IPERC',
            'Permisos_Trabajo',
            'Charlas_5_Minutos',
            'Capacitaciones',
            'Inspecciones',
            'Accidentes',
            'Incidentes',
            'Reportes_SSOMA',
            'EPP',
            'SCTR',
            'Plan_Seguridad',
        ],
    ],
    [
        'nombre' => 'MEDIO_AMBIENTE',
        'descripcion' => 'Monitoreos, residuos, evidencias y planes ambientales.',
        'subcarpetas' => [
            'Monitoreos',
            'Manejo_Residuos',
            'Evidencias',
            'Informes_Ambientales',
            'Impactos_Ambientales',
            'Plan_Manejo_Ambiental',
        ],
    ],
    [
        'nombre' => 'OFICINA_TECNICA',
        'descripcion' => 'RFI, consultas técnicas, submittals y planos de campo.',
        'subcarpetas' => [
            'RFI',
            'Consultas_Tecnicas',
            'Compatibilizacion',
            'Control_Cambios',
            'Submittals',
            'Planos_Campo',
            'Informes_Tecnicos',
            'Planos_AsBuilt',
        ],
    ],
    [
        'nombre' => 'PLANEAMIENTO_Y_CONTROL',
        'descripcion' => 'Cronograma maestro, lookahead, curva S, avances y KPIs.',
        'subcarpetas' => [
            'Cronograma_Maestro',
            'Lookahead',
            'Curva_S',
            'Avance_Diario',
            'Avance_Semanal',
            'Avance_Mensual',
            'Ruta_Critica',
            'KPI',
            'Reportes_Control',
        ],
    ],
    [
        'nombre' => 'TOPOGRAFIA',
        'descripcion' => 'Levantamientos, replanteos, coordenadas y modelos digitales.',
        'subcarpetas' => [
            'Levantamientos',
            'Replanteos',
            'Coordenadas',
            'Informes_Topograficos',
            'Modelos_Digitales',
        ],
    ],
    [
        'nombre' => 'EQUIPOS_Y_MAQUINARIA',
        'descripcion' => 'Inventario, mantenimiento, certificados y operadores.',
        'subcarpetas' => [
            'Inventario',
            'Mantenimiento',
            'Certificados',
            'Checklists',
            'Horometros',
            'Operadores',
        ],
    ],
    [
        'nombre' => 'RECURSOS_HUMANOS',
        'descripcion' => 'Personal, contratos, asistencia, exámenes y legajos.',
        'subcarpetas' => [
            'Personal',
            'Contratos',
            'Asistencia',
            'Examenes_Medicos',
            'Capacitaciones',
            'SCTR',
            'Legajos',
        ],
    ],
    [
        'nombre' => 'SUBCONTRATISTAS',
        'descripcion' => 'Contratos, valorizaciones, seguros y conformidades.',
        'subcarpetas' => [
            'Contratos',
            'Valorizaciones',
            'Seguros',
            'Documentacion_SSOMA',
            'Informes',
            'Conformidades',
        ],
    ],
    [
        'nombre' => 'PANEL_FOTOGRAFICO',
        'descripcion' => 'Avances diarios/semanales, incidencias, evidencias y drone.',
        'subcarpetas' => [
            'Avance_Diario',
            'Avance_Semanal',
            'Incidencias',
            'Evidencias',
            'Drone',
        ],
    ],
    [
        'nombre' => 'INFORMES',
        'descripcion' => 'Informes diarios, semanales, mensuales y especiales.',
        'subcarpetas' => [
            'Informes_Diarios',
            'Informes_Semanales',
            'Informes_Mensuales',
            'Informes_Especiales',
            'Informes_Supervision',
        ],
    ],
    [
        'nombre' => 'BIM',
        'descripcion' => 'Modelos IFC, coordinación, clash detection y BIM 4D/5D.',
        'subcarpetas' => [
            'Modelos_IFC',
            'Coordinacion',
            'Clash_Detection',
            'BIM_4D',
            'BIM_5D',
        ],
    ],
    [
        'nombre' => 'LIQUIDACION_Y_CIERRE',
        'descripcion' => 'Recepción, conformidad, liquidación y dossier final.',
        'subcarpetas' => [
            'Recepcion_Obra',
            'Conformidad',
            'Liquidacion',
            'Dossier_Final',
            'Planos_AsBuilt',
            'Cierre_Contractual',
        ],
    ],
];
